// <auto-generated />
using System;
using Farrellsoft.Example.SurveyDataLoad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farrellsoft.Example.SurveyDataLoad.Migrations
{
    [DbContext(typeof(SurveyDbContext))]
    [Migration("20251216170802_all rating columns allow null")]
    partial class allratingcolumnsallownull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Farrellsoft.Example.SurveyDataLoad.Entities.RnpsSurveyRecord", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short?>("Age")
                        .HasColumnType("smallint");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLowIncome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PartnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PriceComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReliabilityComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReliabilityRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SurveyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SurveyMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurveySeason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("SurveyYear")
                        .HasColumnType("smallint");

                    b.Property<string>("TransparencyComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransparencyRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordId");

                    b.ToTable("RnpsSurveyRecords", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
